### ISSUE TITLE
Error when running netkeeper

### ISSUE THREAD

**Issue by j-broo** [Salamek/netkeeper#1]
I've installed Netkeeper successfully (I think), but get the following error when I try to run it:

```
Traceback (most recent call last):
  File "/usr/bin/netkeeper", line 33, in <module>
    sys.exit(load_entry_point('netkeeper==2.0.2', 'console_scripts', 'netkeeper')())
  File "/usr/lib/python3/dist-packages/netkeeper/__main__.py", line 5, in main
    from netkeeper.bin.netkeeper import main as _main  # pylint: disable=import-outside-toplevel
  File "/usr/lib/python3/dist-packages/netkeeper/bin/netkeeper.py", line 37, in <module>
    from yaml import load, FullLoader
ImportError: cannot import name 'FullLoader' from 'yaml' (/usr/lib/python3/dist-packages/yaml/__init__.py)
```

My system info:
```
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 0010
Serial          : 0000000079c02fa2
Model           : Raspberry Pi Model B Plus Rev 1.2
```

Any help would be appreciated.

**Comment by Salamek** [comment]
That is weird... What OS are you using?

**Comment by j-broo** [comment]
`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"`

**Comment by j-broo** [comment]
I think this is the issue. 

[https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader](https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader)

My distro has an older version of YAML:
```
Python 3.7.3 (default, Oct 31 2022, 14:04:00)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.__version__
'3.13'
```

`apt upgrade` shows all packages up to date so will need to figure out how to update YAML manually.

**Comment by Salamek** [comment]
Well stable debian(Raspbian) is version 11... maybe time to upgrade your OS?
Here is some howto https://www.linuxuprising.com/2021/11/how-to-upgrade-raspberry-pi-os-10.html (not tested, make sure your board is compatible)

(I don't think that it is feasible to adding some backward compatibility code to support oldstable debian)

**Comment by j-broo** [comment]
I actually followed this guide earlier to do an in-place uprgade to Bullseye. It all seemed to have worked but now the RPi won't boot after a reboot :(

I'll have to solve the upgrade issue first then I'll post an update on this issue...

**Comment by j-broo** [comment]
OK, after I re-flashed my SD card with bullseye (upgrade from buster was unsuccessful), I get the following now when running netkeeper:

```
root@J-Pi:/etc/netkeeper# ls
config.yml
root@J-Pi:/etc/netkeeper# nano config.yml
root@J-Pi:/etc/netkeeper# netkeeper run
Traceback (most recent call last):
  File "/usr/bin/netkeeper", line 33, in <module>
    sys.exit(load_entry_point('netkeeper==2.0.2', 'console_scripts', 'netkeeper')())
  File "/usr/lib/python3/dist-packages/netkeeper/__main__.py", line 6, in main
    _main()
  File "/usr/lib/python3/dist-packages/netkeeper/bin/netkeeper.py", line 416, in main
    getattr(command, 'chosen')()  # Execute the function specified by the user.
  File "/usr/lib/python3/dist-packages/netkeeper/bin/netkeeper.py", line 271, in run
    options = parse_options()
  File "/usr/lib/python3/dist-packages/netkeeper/bin/netkeeper.py", line 152, in parse_options
    config_obj = get_config(config_class_string)
  File "/usr/lib/python3/dist-packages/netkeeper/bin/netkeeper.py", line 122, in get_config
    raise Exception('No configuration file was found!')
Exception: No configuration file was found!
```

But the config.yml file is there?

**Comment by Salamek** [comment]
Should be fixed in latest release, please try...

**Comment by j-broo** [comment]
Thanks, that update worked:

```
Unpacking netkeeper (2.0.3-1) over (2.0.2-1) ...
Setting up netkeeper (2.0.3-1) ...
root@J-Pi:/home/pi# netkeeper run
Loading config from /etc/netkeeper/config.yml
I0423 08:58:43.760 9446 netkeeper.py:349] All is OK, sleeping for 60s
```

So, moral of the story is it only works on Bullseye.
